print ("##############################")
print ("#                            #")
print ("# Andra Braputra Akbar Saleh #")
print ("#      2310817210001         #")
print ("#                            #")
print ("##############################")